#! /bin/bash
# postinst script for jens-cli
#

echo "======================================="
echo "||        Jens-cli installed.        ||"
echo "||   Available commands:             ||"
echo "||       - drplay                    ||"
echo "||       - drshow                    ||"
echo "||       - drbenchmark               ||"
echo "|| For help see manpages of commands ||"
echo "======================================="
echo "||      PASSWORDS HAVE CHANGED!      ||"
echo "||      GrafanaUI = admin:admin      ||"
echo "======================================="