#! /bin/bash
# postinst script for jens-cli
#

echo "    ======================================="
echo "    ||        Jens-cli installed.        ||"
echo "    ||   Available commands:             ||"
echo "    ||       - drplay                    ||"
echo "    ||       - drshow                    ||"
echo "    ||       - drbenchmark               ||"
echo "    || For help see manpages of commands ||"
echo "    ======================================="
echo "---------------------------------------------"
echo "|                                           |"
echo "|   Please update psql/ grafana container   |"
echo "|             1. docker stop ...            |"
echo "|       2. docker pull edgeaml/drdash       |"
echo "|     3. docker run ... (see dockerHub)     |"
echo "|                                           |"
echo "|          PASSWORDS HAVE CHANGED!          |"
echo "|          GrafanaUI = admin:admin          |"
echo "---------------------------------------------"
