[tccommands]
  markfree=4 #in Millisecond
  markfull=14 #in Millisecond
  # Size of custom Queue in packets
  queuesizepackets=10000
  # AddonLatency in MS to add to all packets
  extralatency=0
  # Mark non-ect(1) Traffic as enabled
  l4sEnabledPreMarking=false
  # Mark the first packets with special ect
  signalDrpStart=false

[postgres]
  dbname = "l4s_measure"
  host = "localhost"
  password = "changeDefaultPassword"
  port = 5432
  user = "edge"

[drp]
  # MinimumDataRate for patterns
  minRateKbits = 500
  #Phase in MS before Networkshaping /DRP takes effect
  WarmupBeforeDrpMs = 2000

[drshow]
  scalePlots=true #instead of scrolling
  exportPath="/etc/jens-cli"
  #Used for filtering of flows in pipemode
  FilterLevel0Until=7       
  #Adds to Level0Until: Min count of flows for filter to kick in action
  FilterLevel1AddUntil=6    
  #Filter minium samples to display flow
  FilterLevel1MinSamples=15 
  #Or maximum time passed since last sample was received
  FilterLevel1SecsPassed=30 
  FilterLevel2AddUntil=6
  FilterLevel2MinSamples=15
  FilterLevel2SecsPassed=20
  FilterLevel3AddUntil=6
  FilterLevel3MinSamples=25
  FilterLevel3SecsPassed=10
